### ISSUE TITLE
TinyMCE Modal window textfields lost focus in Firefox 12

### ISSUE THREAD

**Issue by jankor** [harrydeluxe/extjs-ux#6]
In tinymce example add any button that opens modal window (ie Media, Images). Click that button and try to fill any textfield, textarea or select. Firefox 12 seems to switch focus immediately after an item is being clicked, making the action impossible to complete.

**Comment by harrydeluxe** [comment]
ok is fixed.

**Comment by r1561** [comment]
Thank you for your work, TinyMCE extension looks great. But maybe this same problem still exists in  firefox 13.0.1? Just tried html-button from demo (and also from downloaded code) and I could not write anything to html source window. No error to javascript console. Could you take a look?

**Comment by harrydeluxe** [comment]
Ok, works now with firefox 13.0.1. Thanks for the note.
